version: '3.8'

services:
  scanner:
    ## image: derhenning/tgtg:latest-alpine
    ## pre build image from docker hub
    ## image: tgtg-scanner:latest                   ## locally build image
    build:                                       ## build image with compose
       context: .
       dockerfile: docker/Dockerfile.alpine
    env_file:
      - .env
    volumes:
      - tokens:/tokens
    ports:
      # Expose the metrics port to the host and other containers
      - "8000:8000"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana
    env_file:
      - .env
    depends_on:
      - prometheus
volumes:
  prom_data:
  tokens:
  grafana-storage:
